# Minimal config for daily csv creation from 4 sensors.

# Basic node identity
node_id: "Node7"
timezone: "America/Toronto"

# Sampling interval in seconds
tick_seconds: 1

# Sensor configuration
sensors:
  pms1:
    enabled: true
    port: "/dev/ttyAMA0"      # PMS #1 on GPIO0/1 â†’ /dev/ttyAMA0

  pms2:
    enabled: true
    port: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"      # PMS #2 connected by USB

  opc:
    enabled: true
    spi_bus: 0                # SPI bus number
    spi_device: 0             # SPI chip select (CE0)
    spi_max_speed: 5000000    # optional, matches OPCN3 default

  bme:
    enabled: true
    i2c_bus: 1
    address: 0x77             # BME688 at 0x76 (SDO tied low)

  so2:
    enabled: true
    i2c_bus: 1
    address: 0x74
